version: "3.7"

services:
  frontend:
    container_name: "frontend"
    build:
      context: ./frontend
    ports:
      - 25543:4173

  backend:
    container_name: "backend"
    environment:
      - OPEN_AI_API_KEY=
    build:
      context: ./backend
    ports:
      - 25544:8080
